name: CI

on: [push, pull_request]

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run test:unit:coverage
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: target/coverage/coverage-final.json
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Check source code
        run: |
          npm run lint
          npm run copy:paste:detector
      - name: Compile source code
        run: npm run compile
      - name: Build application
        run: npm run build
      - name: Quickmetrics
        uses: ./
        with:
          name: quickmetrics.action.usage
          api-key: ${{ secrets.QUICKMETRICS_API_KEY }}
